const progressActionsTypes = {
  READ_USER_PROGRESS_START: 'READ_USER_PROGRESS_START',
  WRITE_USER_PROGRESS_START: 'WRITE_USER_PROGRESS_START',
  READ_USER_PROGRESS_SUCCESS: 'READ_USER_PROGRESS_SUCCESS',
  WRITE_USER_PROGRESS_SUCCESS: 'WRITE_USER_PROGRESS_SUCCESS',
  READ_USER_PROGRESS_FAIL: 'READ_USER_PROGRESS_FAIL',
  WRITE_USER_PROGRESS_FAIL: 'WRITE_USER_PROGRESS_FAIL',
  PROGRESS_TRACKING: 'PROGRESS_TRACKING',
  TIME_TRACKING: 'TIME_TRACKING',
  PROGRESS_REFRESH: 'PROGRESS_REFRESH',
};

export default progressActionsTypes;
